class SharedConstants {
  static const TOKEN = "token";
  static const APPSFLYER_ID = "appfyler_uid";
  static const ISLOGIN = "login"; //Type Bool
  static const PROFILE_ID = "profile_id";
  static const APPFLYER_PROFILE_ID = "appflyer_profile_id";
  static const MIN_LOAN = "min_loan";
  static const MIN_TENURE = "min_tenure";
  static const MAX_LOAN = "max_loan";
  static const MAX_TENURE = "max_tenure";
  static const FCM_TOKEN = "fcm_token";
  static const MOBILE = "mnumber";
  static const CURRENTSCREEN = "current";
  static const AADHAAR = "aadhaar";
  static const PANCARD = "pan";
  static const OUT_AMT = "out_amt";
  static const DIS_AMT = "dis_amt";
  static const REPAYMENT_DATE = "repayment_date";
  static const REPAYMENT_AMT = "repayment_amt";
  static const REPAYMENT_HISTORY = "repayment_history";
  static const DIS_DATE = "dis_date";
  static const LOAN_STATUS = "loan_status";
  static const REMAINING_DAYS = "remaining_days";
  static const CONTACT_US_NUMBER = "contact_us_number";
  static const CONTACT_US_WHATSAPP = "contact_us_whatsapp";
  static const CONTACT_US_EMAIL = "contact_us_email";
  static const PROFILE_PIC = "profileImage";
  static const BANNERS = "banners";
  static const IS_BANNERS = "is_banners";
  static const IS_EDITABLE = "is_editable";
  static const NAMEONPANCARD = "nameonpan";
  static const DOB = "dob";
  static const BANKNUMBER = "banknumber";
  static const IFSC = "ifsc";
  static const BRANCH_NAME = "branch_name";
  static const EMAIL = "email";
  static const NAME = "name";
  static const FULL_NAME = "fullname";
  static const SPOUSE_NAME = "spouse_name";
  static const SPOUS_NUMBER = "spouse_no";
  static const CIBIL_ID = "cibil_id";
  static const SALARY = "salary";
  static const CIBIL = "cibil";
  static const SALARY_DATE = "salary_data";
  static const ADDRESS1 = "address1";
  static const ADDRESS_OFFICE1 = "addressoffice1";
  static const ADDRESS_OFFICE2 = "addressoffice2";
  static const OFFICE_EMAIL = "office_email";
  static const DEPT_NAME = "dept_name";
  static const DESIGNATION = "designation";
  static const EMP_SINCE = "emp_since";
  static const SERVICE_TENURE = "service_tenure";
  static const ADDRESS2 = "address2";
  static const LANDMARK = "address3";
  static const OFFICE_LANDMARK = "officeaddress3";
  static const LANDMARK_OFFICE = "address3_office";
  static const RESIDENCETYPE = "residencetype";
  static const MARITALSTATUS = "maritalstatus";
  static const LATLONG = "latlong";
  static const GENDER = "gender";
  static const COMPANYNAME = "companyname";
  static const COMPANYTYPE = "companytype";
  static const SALARY_MODE = "mode";
  static const SALARY_MODE_ID = "mode_id";
  static const WORK_MODE = "workmode";
  static const USER_TYPE = "user_type";
  static const STEP_STAGE = "step_stage";
  static const REJECT_REASON = "reject_reason";
  static const STEP_COMPLETE_PERCENT = "step_complete_percent"; //Type Int
  static const CITY = "city";
  static const STATE = "state";
  static const IS_REGESTRATED = "registration_successful"; //Type String
  static const IS_APPLIED = "application_submitted"; //Type String
  static const ELIGIBLE = "eligible"; //Type Bool
  static const PINCODE = "pincode";
  static const EMP_PINCODE = "emp_pincode";
  static const EMP_TYPE = "emp_type";
  static const EMP_TYPE_ID = "emp_type_id";
  static const NAMEONBANK = "name_onbank";
  static const ALL_LEADS = "allLeads";
  static const LEAD_CUSTOMER = "lead_customer";
  static const LOAN_AMOUNT = "loanAmount";
  static const LOAN_NO = "loanNo";
  static const LOAN_LEAD_ID = "loanLeadId";
  static const PURPOSE = "purpose";
  static const TENURE = "tenure";
  static const THEME = "isDarkMode";
  static const UTM_SOURCE = "utm_source";

  //General Constant
 static const Company_Address = "Office No-101, First Floor,NN Mall, Mangalam Palace,Sector-3, Rohini Delhi-110085";
 static const Company_Name = "Baid Stock Broking Services Private Limited";
 static const Brand_Name = "Salarytopup ";
 static const ARD_Package_Name = "com.salarytopup.salarytopup";
 static const IOS_App_Id = "";
 static const instagram = "https://www.instagram.com/salarytopup/";
 static const facebook = "https://www.facebook.com/people/salarytopup/";
 static const twitter = "https://x.com/salarytopup";
 static const youtube = "https://www.youtube.com/@salarytopup";
 static const gmaps = 'https://www.google.com/maps/place/NN+Mall/@28.6997176,77.1143893,18z/data=!3m1!5s0x390d03e30a35f7ad:0x81e6780ea7f99861!4m10!1m2!2m1!1sOffice+No-101,+First+Floor,NN+Mall,+Mangalam+Palace,Sector-3,+Rohini+Delhi-110085!3m6!1s0x390d03e30bfaaaab:0x9bf53f2531cf07f4!8m2!3d28.7014315!4d77.1165606!15sClFPZmZpY2UgTm8tMTAxLCBGaXJzdCBGbG9vcixOTiBNYWxsLCBNYW5nYWxhbSBQYWxhY2UsU2VjdG9yLTMsIFJvaGluaSBEZWxoaS0xMTAwODVaUCJOb2ZmaWNlIG5vIDEwMSBmaXJzdCBmbG9vciBubiBtYWxsIG1hbmdhbGFtIHBhbGFjZSBzZWN0b3IgMyByb2hpbmkgZGVsaGkgMTEwMDg1kgEPYnVzaW5lc3NfY2VudGVymgEkQ2hkRFNVaE5NRzluUzBWSlEwRm5TVU5YY2pkUVRITm5SUkFCqgHLARABKlIiTm9mZmljZSBubyAxMDEgZmlyc3QgZmxvb3Igbm4gbWFsbCBtYW5nYWxhbSBwYWxhY2Ugc2VjdG9yIDMgcm9oaW5pIGRlbGhpIDExMDA4NSgAMh8QASIb3N3nebw29J8Nr-yHtxxARiMnHx_fHocipwQIMlIQAiJOb2ZmaWNlIG5vIDEwMSBmaXJzdCBmbG9vciBubiBtYWxsIG1hbmdhbGFtIHBhbGFjZSBzZWN0b3IgMyByb2hpbmkgZGVsaGkgMTEwMDg14AEA-gEECAAQIg!16s%2Fg%2F11hbv9xvzf?entry=ttu&g_ep=EgoyMDI1MDUwNi4wIKXMDSoASAFQAw%3D%3D';
 static const razorpayKey ="rzp_live_L7iGFEiE6MGnlN";
 static const Company_Number ="+919643336036";
 static const Company_WaNumber ="+919643336036";
 static const Company_Email ="info@salarytopup.com";
 static const Company_Website ="https://salarytopup.com";
 static const Privacy_Policy_Url ="https://salarytopup.com/privacypolicy";
 static const Terms_Condition_Url ="https://salarytopup.com/termsandconditions";

}
